export const products = [
  {
    id: "gramophone", slug: "victor-horn-gramophone", sku: "OSM-SND-024", name: "Victor Horn Gramophone",
    era: "Circa 1924", year: 1924, price: 1280, cost: 610, category: "Sound", brand: "Victor Talking Machine Co.",
    image: "/images/gramophone.png", note: "Restored mechanism", stock: 3, status: "In stock", location: "Vault A · Shelf 04",
    source: "Harrington Estate, Beacon NY", acquired: "2026-03-18", provenance: "Single-family ownership since 1951; estate inventory label retained.",
    origin: "Camden, New Jersey, USA", maker: "Victor Talking Machine Company", materials: "Brass, steel, lacquered oak",
    dimensions: "72 × 48 × 46 cm", weight: "18.4 kg", condition: "Very good", conditionNotes: "Stable lacquer wear, small horn crease, movement serviced and tested.",
    authenticity: "Movement and cabinet numbers consistent with 1924 production records.", grade: "A−", lastGraded: "2026-05-12",
    restorer: "M. Bell Mechanical Conservation", restoration: "Governor cleaned, spring lubricated, soundbox gasket replaced.",
    shippingClass: "Large / fragile", insuredValue: 1500, views: 384, favorites: 42, rating: 4.9, reviewCount: 7,
    description: "A hand-cranked Victor gramophone with an aged brass horn, black lacquer case, and carefully serviced mechanism.",
    details: ["Original Victor Exhibition soundbox", "Hand-cranked spring mechanism", "Professionally serviced", "Research dossier included"],
  },
  {
    id: "pocket-watch", slug: "engraved-hunter-watch", sku: "OSM-CUR-092", name: "Engraved Hunter Watch",
    era: "Circa 1892", year: 1892, price: 860, cost: 365, category: "Curios", brand: "Waltham",
    image: "/images/pocket-watch.png", note: "Sterling silver", stock: 1, status: "Low stock", location: "Safe 2 · Drawer 06",
    source: "Bell & Finch Auctions, Boston", acquired: "2026-04-02", provenance: "Monogrammed J.R.H.; auctioned from the Hale family collection.",
    origin: "Waltham, Massachusetts, USA", maker: "American Waltham Watch Co.", materials: "Sterling silver, enamel, blued steel",
    dimensions: "52 mm case", weight: "114 g", condition: "Excellent", conditionNotes: "Light case wear; enamel dial free of hairlines; keeps time within 45 seconds/day.",
    authenticity: "Serial number dates the Grade 820 movement to 1891–1892.", grade: "A", lastGraded: "2026-06-03",
    restorer: "Harbor Horology", restoration: "Movement cleaned and regulated; no cosmetic polishing.",
    shippingClass: "Small / high value", insuredValue: 1050, views: 517, favorites: 88, rating: 4.8, reviewCount: 12,
    description: "A sterling silver hunter-case pocket watch with hand engraving, enamel dial, and original chain.",
    details: ["Sterling silver case", "17-jewel mechanical movement", "Original chain included", "Timekeeping report supplied"],
  },
  {
    id: "porcelain-vase", slug: "cobalt-porcelain-vase", sku: "OSM-DEC-080", name: "Cobalt Porcelain Vase",
    era: "Circa 1880", year: 1880, price: 640, cost: 240, category: "Decor", brand: "Sèvres School",
    image: "/images/porcelain-vase.png", note: "Hand-painted", stock: 2, status: "In stock", location: "Vault B · Cabinet 01",
    source: "Maison Lenoir, Paris", acquired: "2026-02-27", provenance: "Private Paris collection; dealer invoice and 1978 photograph included.",
    origin: "France", maker: "Unmarked, Sèvres-school decorator", materials: "Hard-paste porcelain, cobalt glaze, gilt",
    dimensions: "38 × 17 cm", weight: "2.1 kg", condition: "Good", conditionNotes: "Stable craquelure and gilt rubbing; no cracks; old restored rim chip under UV.",
    authenticity: "Paste, decoration, and wear are consistent with late-19th-century French production.", grade: "B+", lastGraded: "2026-04-21",
    restorer: "Atelier Voss", restoration: "Historic rim fill stabilized; no overpainting added.",
    shippingClass: "Medium / fragile", insuredValue: 800, views: 269, favorites: 31, rating: 4.7, reviewCount: 5,
    description: "A hand-painted porcelain vase with deep cobalt decoration, aged gilt edging, and fine surface craquelure.",
    details: ["Hand-painted porcelain", "Original gilt details", "Stable age-related craquelure", "Museum-safe packing"],
  },
  {
    id: "mantel-clock", slug: "french-marble-mantel-clock", sku: "OSM-CLK-881", name: "French Marble Mantel Clock",
    era: "Circa 1881", year: 1881, price: 2150, cost: 980, category: "Clocks", brand: "Japy Frères",
    image: "/images/hero-collection.png", note: "Eight-day movement", stock: 1, status: "Low stock", location: "Vault A · Shelf 01",
    source: "Rutherford House Sale, Kent", acquired: "2026-01-14", provenance: "Rutherford family drawing room; photographed in a 1928 estate album.",
    origin: "Paris, France", maker: "Japy Frères", materials: "Belgian black marble, gilt bronze, enamel",
    dimensions: "44 × 31 × 15 cm", weight: "12.7 kg", condition: "Very good", conditionNotes: "Minor edge nicks; dial clean; strikes correctly on bell.",
    authenticity: "Stamped movement and pendulum; case construction consistent with 1880s Paris work.", grade: "A−", lastGraded: "2026-05-30",
    restorer: "M. Bell Mechanical Conservation", restoration: "Movement overhauled; replacement suspension spring documented.",
    shippingClass: "Large / fragile", insuredValue: 2600, views: 690, favorites: 104, rating: 5, reviewCount: 4,
    description: "A substantial French architectural mantel clock in black marble with gilt-bronze mounts and an eight-day bell-striking movement.",
    details: ["Signed Japy Frères movement", "Original pendulum and key", "Eight-day bell strike", "Conservation report included"],
  },
  {
    id: "field-camera", slug: "mahogany-field-camera", sku: "OSM-PHO-905", name: "Mahogany Field Camera",
    era: "Circa 1905", year: 1905, price: 1120, cost: 475, category: "Photography", brand: "Thornton-Pickard",
    image: "/images/hero-collection.png", note: "Original brass lens", stock: 0, status: "Sold", location: "Archive · Sold 14",
    source: "Northlight Studio Archive, Chicago", acquired: "2025-11-09", provenance: "Working studio equipment until 1948; studio stamp under baseboard.",
    origin: "Manchester, England", maker: "Thornton-Pickard", materials: "Mahogany, brass, leather bellows, optical glass",
    dimensions: "36 × 29 × 18 cm folded", weight: "4.8 kg", condition: "Display condition", conditionNotes: "Bellows show pinholes; rack movement works; lens has light haze.",
    authenticity: "Maker plaque, fittings, and lens serial are period-correct.", grade: "B", lastGraded: "2026-02-08",
    restorer: "In-house conservation", restoration: "Dry cleaned, brass waxed, no bellows replacement.",
    shippingClass: "Medium", insuredValue: 1350, views: 812, favorites: 126, rating: 4.9, reviewCount: 9,
    description: "A mahogany half-plate field camera retaining its brass lens, focusing screen, and richly aged leather bellows.",
    details: ["Original brass lens", "Ground-glass screen intact", "Working rack focus", "Display and conservation notes included"],
  },
];

export const productBySlug = (slug) => products.find((product) => product.slug === slug);
