export const products = [
  {
    id: "gramophone",
    slug: "victor-horn-gramophone",
    name: "Victor Horn Gramophone",
    era: "Circa 1924",
    price: 1280,
    category: "Sound",
    image: "/images/gramophone.png",
    note: "Restored mechanism",
    stock: 1,
    description: "A portable hand-cranked gramophone with an aged brass horn, black lacquer case, and carefully serviced mechanism.",
    details: ["Brass and lacquered timber", "Hand-cranked mechanism", "Professionally serviced", "Insured worldwide delivery"],
  },
  {
    id: "pocket-watch",
    slug: "engraved-hunter-watch",
    name: "Engraved Hunter Watch",
    era: "Circa 1892",
    price: 860,
    category: "Curios",
    image: "/images/pocket-watch.png",
    note: "Sterling silver",
    stock: 1,
    description: "A sterling silver hunter-case pocket watch with hand engraving, enamel dial, and original chain.",
    details: ["Sterling silver case", "Mechanical movement", "Original chain included", "Condition report supplied"],
  },
  {
    id: "porcelain-vase",
    slug: "cobalt-porcelain-vase",
    name: "Cobalt Porcelain Vase",
    era: "Circa 1880",
    price: 640,
    category: "Decor",
    image: "/images/porcelain-vase.png",
    note: "Hand-painted",
    stock: 1,
    description: "A hand-painted porcelain vase with deep cobalt decoration, aged gilt edging, and fine surface craquelure.",
    details: ["Hand-painted porcelain", "Original gilt details", "Stable age-related craquelure", "Museum-safe packing"],
  },
];

export const productBySlug = (slug) => products.find((product) => product.slug === slug);
